language: csharp
script:
  - xbuild /p:Configuration=Debug ConsoleApp.sln
  - mono ./nunitconsole/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe
before_install:
 - sudo apt-get install nunit-console
before_script:
 - nuget restore ConsoleApp.sln
after_script:
  - nunit-console Tests/bin/Release/Tests.dll