language: csharp
script:
  - xbuild /p:Configuration=Debug ConsoleApp.sln
before_install:
 - sudo apt-get install nunit-console
before_script:
 - nuget restore ConsoleApp.sln
after_script:
  - nunit-console Tests/bin/Release/Tests.dll